@user_url = http://localhost:8080/api/user/
@admin_url = http://localhost:8080/api/admin/

// USER OPERATIONS

// findByUserIdUser
GET {{user_url}}1/routine

// addRoutineUser
###
POST {{user_url}}routine
Content-Type: application/json

{
  "title": "Routine 1",
  "userId": 1,
  "muscles": [
    "TRAPEZIUS",
    "UPPER_BACK",
    "LOWER_BACK"
  ]
}

// addRoutineUser unhappy path
###
POST {{user_url}}routine
Content-Type: application/json

{
  "muscles": [
  ]
}

// updateRoutineUser
###
PUT {{user_url}}routine/1
Content-Type: application/json

{
  "routineId": 1,
  "title": "Routine 2",
  "userId": 1,
  "muscles": [
    "TRAPEZIUS",
    "UPPER_BACK",
    "LOWER_BACK",
    "NECK"
  ]
}

// updateRoutineUser unhappy path
###
PUT {{user_url}}routine/99
Content-Type: application/json

{
  "routineId": 99,
  "title": "Routine 2",
  "userId": 1,
  "muscles": [
    "TRAPEZIUS",
    "UPPER_BACK",
    "LOWER_BACK",
    "NECK"
  ]
}

// deleteRoutineUser
###
DELETE {{user_url}}routine/1



// ADMIN OPERATIONS

// findall
###
GET {{admin_url}}routin


// updateRoutineAdmin
###
PUT {{admin_url}}routine/1
Content-Type: application/json

{
  "routineId": 1,
  "title": "Routine 2",
  "userId": 1,
  "muscles": [
    "TRAPEZIUS",
    "UPPER_BACK",
    "LOWER_BACK",
    "NECK"
  ]
}

// updateRoutineAdmin unhappy path
###
PUT {{admin_url}}routine/99
Content-Type: application/json

{
  "routineId": 99,
  "title": "Routine 2",
  "userId": 1,
  "muscles": [
    "TRAPEZIUS",
    "UPPER_BACK",
    "LOWER_BACK",
    "NECK"
  ]
}

// deleteRoutineAdmin
###
DELETE {{admin_url}}routine/1
