@user_url = http://localhost:8080/api/user
@admin_url = http://localhost:8080/api/admin

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6Miwic3ViIjoiZHRlc3RlckBlbWFpbC5jb20iLCJpYXQiOjE3NTMyNTA1MDksImV4cCI6MTc1MzI1MjMwOX0.5gDYYzmWrol2fgOl4iKaKSi_yKz4JV5aDi_dy0DR6iI
@jwt_admin = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJ1c2VySWQiOjEsInN1YiI6ImRvdWdAZ21haWwuY29tIiwiaWF0IjoxNzUzMjUwNTI5LCJleHAiOjE3NTMyNTIzMjl9.oTfnIpZvwv2JUtMSaNOEK0j3Ly9PzBzS8WnFFjGkaQk

### Get my routines
GET {{user_url}}/me/routine
Authorization: Bearer {{jwt_admin}}

### Add a new routine
POST {{user_url}}/me/routine
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "title": "Morning abs user",
  "muscles": ["LOWER_BACK", "UPPER_BACK"]
}

### Update a routine by ID
PUT {{user_url}}/me/routine/1
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "routineId": 1,
  "userId": 1,
  "title": "zebra",
  "muscles": ["FOREARM"]
}

### Delete a routine by ID
DELETE {{user_url}}/routine/3
Authorization: Bearer {{jwt_admin}}

### Admin: Get all routines
GET {{admin_url}}/routine
Authorization: Bearer {{jwt_admin}}
